export interface CreateClassModel{
    className:string;
    noOfStudents:string;
    startDate:string;
    endDate:string;
    schoolId:string;
    serviceTypeId:string;
    accessibilityId:string;
    description:string;
    price:number;
    currency:string;
    rating:number;
    thumbnailUrl:string;
    languageIds:any;
    teacherIds:any;
    studentIds:any;
    disciplineIds:any;
    classUrl:string;
    tags:string;
    createdById:string;
}
